### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(HELLOContent)
add_subdirectory(HELLO)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	HELLOContentplugin
	HELLOplugin)