### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(WORLDContent)
add_subdirectory(WORLD)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	WORLDContentplugin
	WORLDplugin)