name: Publish images

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io/vergemotorcycles

jobs:
  build-and-push-image:
    runs-on: ubuntu-arm64
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: qt-hello
            src_dir: app-hello
          - image: qt-world
            src_dir: app-world
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SRC_DIR=${{ matrix.src_dir }}
